<a href="https://colab.research.google.com/github/Deeksha040/ML/blob/main/backpropogation_ipyng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

y=x^2

In [ ]:
x=torch.tensor(4.0,requires_grad=True)

In [ ]:
x

tensor(4., requires_grad=True)

In [ ]:
y=x**2

In [ ]:
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
# backpropogation y=2X
y.backward(gradient=None, retain_graph=None, create_graph=False)

In [ ]:
print(x.grad)

tensor(8.)


In [ ]:

lst=[[1.,2.,3,],[4.,5.,6.],[7.,8.,9.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [ ]:
torch_input

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [ ]:
# y=x**3+x**2
# dy=3x**2+2x
y=torch_input**3+torch_input**2
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [ ]:
z=y.sum()
z

tensor(2310., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
torch_input.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])